package be.rlab.search.model

import be.rlab.nlp.model.Language
import be.rlab.search.Hashes.generateId
import java.util.*

/** Represents a document in the Lucene index.
 *
 * @param id Document id generated by [generateId].
 * @param namespace Document namespace.
 * @param language Document language.
 * @param fields List of fields.
 */
data class Document(
    val id: String,
    val namespace: String,
    val language: Language,
    val fields: List<Field>
) {
    companion object {
        fun new(
            namespace: String,
            language: Language,
            vararg fields: Field
        ): Document =
            Document(
                id = generateId(UUID.randomUUID(), language),
                namespace = namespace,
                language = language,
                fields = fields.toList()
            )
    }

    operator fun get(name: String): String? {
        return fields.find { field ->
            field.name == name
        }?.value
    }
}