package be.rlab.search.model

import be.rlab.nlp.model.Language
import be.rlab.search.Hashes.generateId
import java.util.*

/** Represents a document in the Lucene index.
 */
data class Document(
    /** Document id generated by [generateId] */
    val id: String,
    /** Document namespace that represents this collection. */
    val namespace: String,
    /** List of fields */
    val fields: List<Field>
) {
    companion object {
        fun new(
            namespace: String,
            language: Language,
            vararg fields: Field
        ): Document =
            Document(
                id = generateId(UUID.randomUUID(), language),
                namespace = namespace,
                fields = fields.toList()
            )
    }

    inline operator fun<reified T> get(name: String): T? {
        return fields.find { field ->
            field.name == name
        }?.value as T
    }
}
