package be.rlab.nlp.model

import org.apache.commons.lang3.builder.EqualsBuilder
import org.apache.commons.lang3.builder.HashCodeBuilder

/** Represents a token generated by a Lucene tokenizer.
 * @param start Start position in the document.
 * @param end End position in the document.
 * @param data Token data.
 */
data class Token(
    val start: Int,
    val end: Int,
    val data: CharArray
) {

    fun isEmpty(): Boolean {
        return data.isEmpty()
    }

    override fun equals(other: Any?): Boolean {
        return EqualsBuilder.reflectionEquals(this, other)
    }

    override fun hashCode(): Int {
        return HashCodeBuilder.reflectionHashCode(this)
    }

    override fun toString(): String {
        return String(data)
    }
}
