package be.rlab.nlp.model

/** Represents a token generated by a Lucene tokenizer.
 * @param start Start position in the document.
 * @param end End position in the document.
 * @param data Token data.
 */
data class Token(
    val start: Int,
    val end: Int,
    val data: CharArray
) {

    fun isEmpty(): Boolean {
        return data.isEmpty()
    }

    override fun toString(): String {
        return String(data)
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Token

        if (start != other.start) return false
        if (end != other.end) return false
        if (!data.contentEquals(other.data)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = start
        result = 31 * result + end
        result = 31 * result + data.contentHashCode()
        return result
    }
}
